#!/usr/bin/env bash
#copies a file from your local machine to a host machine

if [ $# -lt 4 ];
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

path_to_file=$1
ip_address=$2
username=$3
path_to_ssh=$4

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
