#!/usr/bin/env bash
# commands to install nginx on webserver

sudo apt-get update -y
sudo apt-get install nginx -y

#allowing nginx on firewall
ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing nginx configurations
sudo nginx -t

sudo service ngix reload
