#!/bin/bash
# bash script that pings an ip address passed as an arguement
#+ it should ping it 5 times

if [ "$#" -eq 0 ]; then
   echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
