#!/usr/bin/env bash
# The script is supposed to configure an ubuntu server
#+ The local host should resolve to 127.0.0.2
#+ Facebook.com should resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
