#!usr/bin/env bash
# The script is used to configure an ubuntu server
#+ The localhost should resolve to 127.0.0.2
#+ facebook.com should resolve to 8.8.8.8

echo "127.0.0.2	localhost" | sudo tee  /etc/hosts
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts
