#!usr/bin/bash
#The script displays all active ipv4 ips
# Get the list of network interfaces on the machine

interfaces=($(ip -o link show | awk -F': ' '{print $2}' | tr '\n' ' '))

# Loop through each interface and get its IPv4 address(es)
for interface in "${interfaces[@]}"; do
    ipv4=($(ip -o -4 addr show dev "$interface" | awk '{print $4}'))

    for ip in "${ipv4[@]}"; do
        echo "Interface $interface has IPv4 address $ip"
    done
done

